# Generated by Django 5.0.3 on 2024-04-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Employee',
        ),
    ]
